INSERT INTO books (title, author, published_year) VALUES
                                                      ('The Catcher in the Rye', 'J.D. Salinger', 1951),
                                                      ('To Kill a Mockingbird', 'Harper Lee', 1960),
                                                      ('Pride and Prejudice', 'Jane Austen', 1813),
                                                      ('1984', 'George Orwell', 1949),
                                                      ('War and Peace', 'Leo Tolstoy', 1869),
                                                      ('Moby-Dick', 'Herman Melville', 1851),
                                                      ('The Great Gatsby', 'F. Scott Fitzgerald', 1925),
                                                      ('The Hobbit', 'J.R.R. Tolkien', 1937),
                                                      ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 1997),
                                                      ('The Lord of the Rings', 'J.R.R. Tolkien', 1954),
                                                      ('Brave New World', 'Aldous Huxley', 1932),
                                                      ('Catch-22', 'Joseph Heller', 1961),
                                                      ('Crime and Punishment', 'Fyodor Dostoevsky', 1866),
                                                      ('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880),
                                                      ('The Picture of Dorian Gray', 'Oscar Wilde', 1890),
                                                      ('Frankenstein', 'Mary Shelley', 1818),
                                                      ('Dracula', 'Bram Stoker', 1897),
                                                      ('The Odyssey', 'Homer', -800),
                                                      ('The Iliad', 'Homer', -750);